### ISSUE TITLE
[BUG] Changing var name removes node connections

### ISSUE THREAD

**Issue by Wardergrip** [mininotallarines/NodeEditor#8] opened 2020-08-07 10:29 UTC
I have encountered my issue doing the following:

1. I made a variable and called it nisl
2. I made a node Get nisl
3. I connected get nisl with a print node
4. I renamed nisl to nils

Result: Get nils was disconnected with the print node.

**Comment by mininotallarines** [comment] 2020-08-07 10:32
Duplicate of #4

**Closed** 2020-09-20 18:30 UTC
Labels: bug, confirmed, duplicate
